### ISSUE TITLE
check code for custom styling of petclinic

### ISSUE THREAD

**Issue by mariodavid** [cuba-platform/guides#21]
It is about the original example:
https://github.com/cuba-platform/cuba-petclinic

As it should serve as a good example it would be great if someone can verify that the internal quality of the SCSS rules and so on are a good example in fact.

**Comment by web-devel** [comment]
LGTM, minor fix: cuba-platform/cuba-petclinic/pull/6

**Comment by mariodavid** [comment]
Cool, thanks. Looks good  - merged
