### ISSUE TITLE
Handle Callout display correctly

### ISSUE THREAD

**Issue by mariodavid** [cuba-platform/guides#40]
Currently in the source code listings the callouts "(1)" are displayed in a way which is not optimal:
<img width="828" alt="bildschirmfoto 2019-02-01 um 08 35 51" src="https://user-images.githubusercontent.com/817400/52109065-723b8380-25fc-11e9-9f0c-c5beefe7ac38.png">

There are currently the following problems:

* the callout in the source code listing is rendered with the same typo and background as the source code itself
* the callout in the source code listing is selectable, which should not be the case for copy & paste of source code snippets

In the official Asciidoc syntax examples the callouts in the source code do not have those problems:

<img width="749" alt="bildschirmfoto 2019-02-01 um 08 38 51" src="https://user-images.githubusercontent.com/817400/52109209-f1c95280-25fc-11e9-8877-5bd4a8005917.png">

see: https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#source-code

I think it is based on our provided styling that broke the default behavior. Actually I can even remember in previous versions of this repository it actually behaved like the official AsciiDoc examples.

**Comment by GoryachevaSvetlana** [comment]
I have added the necessary styles to the guides pages.
